# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: MSBuild@1
  inputs:
    solution: 's/**/*.sln'
    msbuildArchitecture: 'x64'
    clean: true
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.ArtifactsDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(System.ArtifactsDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(9dc2b8bb-02e0-4970-8ed0-ae01e7f25ceb)'
    appType: 'webAppLinux'
    WebAppName: 'cookingassistantapi'
    packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'
    RuntimeStack: 'STATICSITE|1.0'
